language: python
python:
  - "3.6"
env:
  - DJANGO=1.8
  - DJANGO=1.9
services:
  - mongodb
install:
  - pip install .
  - pip install coveralls
script:
  - coverage run --source=sw_rest_auth --omit=sw_rest_auth/tests/helpers.py setup.py test
after_success:
  - coveralls